/* ═══════════════════════════════════════════════════════════════
   AniPet — Character & Animation Registry
   ═══════════════════════════════════════════════════════════════

   HOW TO ADD A CHARACTER:
   1. Add an entry to the CHARACTERS array below.
   2. Put your sprite sheet PNGs in assets/sprites/{characterId}/
      Naming convention: {characterId}_{animationId}.png
      e.g. assets/sprites/dog/dog_idle.png
           assets/sprites/cat/cat_walking.png

   SPRITE SHEET FORMAT:
   - PNG file with frames arranged in a grid (rows × columns)
   - All frames must be the same size
   - Frame order: left → right, top → bottom
   - Set cols, rows, and frameCount for each animation.
     frameCount can be less than cols*rows to skip blank trailing cells.

   ANIMATION IDs (standard set):
     idle | happy | sad | confused | walking | jumping | sleepy | playing | walkin

   The "walkin" animation plays once when the detail view opens,
   then automatically switches to "idle". Set loop: false for it.
═══════════════════════════════════════════════════════════════ */

export const CHARACTERS = [
  {
    id:        'dog',
    name:      'Dog',
    nickname:  'Biscuit',
    emoji:     '🐶',
    cardColor: '#FFE0B2',    // peach
    animations: [
      {
        id:         'idle',
        label:      'Idle',
        emoji:      '😊',
        src:        'assets/sprites/dog/dog_idle.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        8,
        loop:       true,
      },
      {
        id:         'happy',
        label:      'Happy & Excited',
        emoji:      '🎉',
        src:        'assets/sprites/dog/dog_happy.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        12,
        loop:       false,
      },
      {
        id:         'sad',
        label:      'Sad',
        emoji:      '😢',
        src:        'assets/sprites/dog/dog_sad.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        6,
        loop:       false,
      },
      {
        id:         'confused',
        label:      'Confused',
        emoji:      '😕',
        src:        'assets/sprites/dog/dog_confused.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        8,
        loop:       false,
      },
      {
        id:         'walking',
        label:      'Walking',
        emoji:      '🚶',
        src:        'assets/sprites/dog/dog_walking.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        12,
        loop:       false,
      },
      {
        id:         'jumping',
        label:      'Jumping',
        emoji:      '🦘',
        src:        'assets/sprites/dog/dog_jumping.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        10,
        loop:       false,
      },
      {
        id:         'sleepy',
        label:      'Sleepy',
        emoji:      '😴',
        src:        'assets/sprites/dog/dog_sleepy.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        5,
        loop:       false,
      },
      {
        id:         'playing',
        label:      'Playing',
        emoji:      '🎾',
        src:        'assets/sprites/dog/dog_playing.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        12,
        loop:       false,
      },
      {
        id:         'walkin',
        label:      'Walk In',
        emoji:      '✨',
        src:        'assets/sprites/dog/dog_walkin.png',
        cols:       4,
        rows:       4,
        frameCount: 16,
        fps:        12,
        loop:       false,   // plays once, then switches to idle
      },
    ],
  },

  {
    id:        'cat',
    name:      'Cat',
    nickname:  'Mochi',
    emoji:     '🐱',
    cardColor: '#E8D5F5',    // lavender
    animations: [
      {
        id:         'idle',
        label:      'Idle',
        emoji:      '😊',
        src:        'assets/sprites/cat/cat_idle.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        8,
        loop:       true,
      },
      {
        id:         'happy',
        label:      'Happy & Excited',
        emoji:      '🎉',
        src:        'assets/sprites/cat/cat_happy.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        12,
        loop:       false,
      },
      {
        id:         'sad',
        label:      'Sad',
        emoji:      '😢',
        src:        'assets/sprites/cat/cat_sad.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        6,
        loop:       false,
      },
      {
        id:         'confused',
        label:      'Confused',
        emoji:      '😕',
        src:        'assets/sprites/cat/cat_confused.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        8,
        loop:       false,
      },
      {
        id:         'walking',
        label:      'Walking',
        emoji:      '🚶',
        src:        'assets/sprites/cat/cat_walking.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        12,
        loop:       false,
      },
      {
        id:         'jumping',
        label:      'Jumping',
        emoji:      '🦘',
        src:        'assets/sprites/cat/cat_jumping.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
      {
        id:         'sleepy',
        label:      'Sleepy',
        emoji:      '😴',
        src:        'assets/sprites/cat/cat_sleepy.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        4,
        loop:       false,
      },
      {
        id:         'playing',
        label:      'Playing',
        emoji:      '🧶',
        src:        'assets/sprites/cat/cat_playing.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
      {
        id:         'walkin',
        label:      'Walk In',
        emoji:      '✨',
        src:        'assets/sprites/cat/cat_walkin.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
    ],
  },

  {
    id:        'duck',
    name:      'Duck',
    nickname:  'Quacky',
    emoji:     '🦆',
    cardColor: '#FFF9C4',    // sunny yellow
    animations: [
      {
        id:         'idle',
        label:      'Idle',
        emoji:      '😊',
        src:        'assets/sprites/duck/duck_idle.png',
        cols:       4,
        rows:       3,
        frameCount: 12,
        fps:        8,
        loop:       true,
      },
      {
        id:         'happy',
        label:      'Happy & Excited',
        emoji:      '🎉',
        src:        'assets/sprites/duck/duck_happy.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        12,
        loop:       false,
      },
      {
        id:         'sad',
        label:      'Sad',
        emoji:      '😢',
        src:        'assets/sprites/duck/duck_sad.png',
        cols:       3,
        rows:       2,
        frameCount: 6,
        fps:        5,
        loop:       false,
      },
      {
        id:         'confused',
        label:      'Confused',
        emoji:      '😕',
        src:        'assets/sprites/duck/duck_confused.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        8,
        loop:       false,
      },
      {
        id:         'walking',
        label:      'Walking',
        emoji:      '🚶',
        src:        'assets/sprites/duck/duck_walking.png',
        cols:       4,
        rows:       3,
        frameCount: 12,
        fps:        12,
        loop:       false,
      },
      {
        id:         'jumping',
        label:      'Jumping',
        emoji:      '🦘',
        src:        'assets/sprites/duck/duck_jumping.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        10,
        loop:       false,
      },
      {
        id:         'sleepy',
        label:      'Sleepy',
        emoji:      '😴',
        src:        'assets/sprites/duck/duck_sleepy.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        4,
        loop:       false,
      },
      {
        id:         'playing',
        label:      'Playing',
        emoji:      '🎈',
        src:        'assets/sprites/duck/duck_playing.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
      {
        id:         'walkin',
        label:      'Walk In',
        emoji:      '✨',
        src:        'assets/sprites/duck/duck_walkin.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
    ],
  },
];

/* Quick lookup by ID */
export const CHARACTER_MAP = Object.fromEntries(CHARACTERS.map(c => [c.id, c]));
