/* ═══════════════════════════════════════════════════════════════
   AniPet — Character & Animation Registry
   ═══════════════════════════════════════════════════════════════

   HOW TO ADD A CHARACTER:
   1. Add an entry to the CHARACTERS array below.

   LEGACY SPRITE FORMAT (cat/duck):
   - One PNG per animation in assets/sprites/{id}/
   - Per-animation props: src, cols, rows, frameCount, fps, loop

   ATLAS SPRITE FORMAT (dog):
   - One master PNG + one JSON atlas in assets/sprites/{id}/
   - Per-animation props: atlasSrc, atlasJsonSrc, atlasKey, fps, loop
   - JSON uses Texture Packer format: frames keyed "{animKey}_f01", "_f02" …

   ANIMATION IDs (standard set):
     idle | happy | sad | confused | walking | jumping | sleepy | playing | walkin | wave_hi

   The "walkin" animation plays once when the detail view opens,
   then automatically switches to "idle". Set loop: false for it.
═══════════════════════════════════════════════════════════════ */

export const CHARACTERS = [
  {
    id:        'dog',
    name:      'Dog',
    nickname:  'Biscuit',
    emoji:     '🐶',
    cardColor: '#FFE0B2',    // peach
    animations: [
      {
        id:           'idle',
        label:        'Idle',
        emoji:        '😊',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'idle_sitting',
        fps:          8,
        loop:         true,
      },
      {
        id:           'wave_hi',
        label:        'Wave Hi',
        emoji:        '👋',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'wave_hi',
        fps:          8,
        loop:         false,
      },
      {
        id:           'happy',
        label:        'Happy & Excited',
        emoji:        '🎉',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'happy_excited',
        fps:          12,
        loop:         false,
      },
      {
        id:           'sad',
        label:        'Sad',
        emoji:        '😢',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'sad',
        fps:          6,
        loop:         false,
      },
      {
        id:           'confused',
        label:        'Confused',
        emoji:        '😕',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'confused',
        fps:          8,
        loop:         false,
      },
      {
        id:           'walking',
        label:        'Walking',
        emoji:        '🚶',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'walking',
        fps:          12,
        loop:         false,
      },
      {
        id:           'jumping',
        label:        'Jumping',
        emoji:        '🦘',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'jumping',
        fps:          10,
        loop:         false,
      },
      {
        id:           'sleepy',
        label:        'Sleepy',
        emoji:        '😴',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'sleepy',
        fps:          5,
        loop:         false,
      },
      {
        id:           'playing',
        label:        'Playing',
        emoji:        '🎾',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'playing',
        fps:          12,
        loop:         false,
      },
      {
        id:           'walkin',
        label:        'Walk In',
        emoji:        '✨',
        atlasSrc:     'assets/sprites/dog/dog_master.png',
        atlasJsonSrc: 'assets/sprites/dog/dog_master.json',
        atlasKey:     'walk_in',
        fps:          12,
        loop:         false,   // plays once, then switches to idle
      },
    ],
  },

  {
    id:        'cat',
    name:      'Cat',
    nickname:  'Mochi',
    emoji:     '🐱',
    cardColor: '#E8D5F5',    // lavender
    animations: [
      {
        id:         'idle',
        label:      'Idle',
        emoji:      '😊',
        src:        'assets/sprites/cat/cat_idle.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        8,
        loop:       true,
      },
      {
        id:         'happy',
        label:      'Happy & Excited',
        emoji:      '🎉',
        src:        'assets/sprites/cat/cat_happy.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        12,
        loop:       false,
      },
      {
        id:         'sad',
        label:      'Sad',
        emoji:      '😢',
        src:        'assets/sprites/cat/cat_sad.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        6,
        loop:       false,
      },
      {
        id:         'confused',
        label:      'Confused',
        emoji:      '😕',
        src:        'assets/sprites/cat/cat_confused.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        8,
        loop:       false,
      },
      {
        id:         'walking',
        label:      'Walking',
        emoji:      '🚶',
        src:        'assets/sprites/cat/cat_walking.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        12,
        loop:       false,
      },
      {
        id:         'jumping',
        label:      'Jumping',
        emoji:      '🦘',
        src:        'assets/sprites/cat/cat_jumping.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
      {
        id:         'sleepy',
        label:      'Sleepy',
        emoji:      '😴',
        src:        'assets/sprites/cat/cat_sleepy.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        4,
        loop:       false,
      },
      {
        id:         'playing',
        label:      'Playing',
        emoji:      '🧶',
        src:        'assets/sprites/cat/cat_playing.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
      {
        id:         'walkin',
        label:      'Walk In',
        emoji:      '✨',
        src:        'assets/sprites/cat/cat_walkin.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
    ],
  },

  {
    id:        'duck',
    name:      'Duck',
    nickname:  'Quacky',
    emoji:     '🦆',
    cardColor: '#FFF9C4',    // sunny yellow
    animations: [
      {
        id:         'idle',
        label:      'Idle',
        emoji:      '😊',
        src:        'assets/sprites/duck/duck_idle.png',
        cols:       4,
        rows:       3,
        frameCount: 12,
        fps:        8,
        loop:       true,
      },
      {
        id:         'happy',
        label:      'Happy & Excited',
        emoji:      '🎉',
        src:        'assets/sprites/duck/duck_happy.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        12,
        loop:       false,
      },
      {
        id:         'sad',
        label:      'Sad',
        emoji:      '😢',
        src:        'assets/sprites/duck/duck_sad.png',
        cols:       3,
        rows:       2,
        frameCount: 6,
        fps:        5,
        loop:       false,
      },
      {
        id:         'confused',
        label:      'Confused',
        emoji:      '😕',
        src:        'assets/sprites/duck/duck_confused.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        8,
        loop:       false,
      },
      {
        id:         'walking',
        label:      'Walking',
        emoji:      '🚶',
        src:        'assets/sprites/duck/duck_walking.png',
        cols:       4,
        rows:       3,
        frameCount: 12,
        fps:        12,
        loop:       false,
      },
      {
        id:         'jumping',
        label:      'Jumping',
        emoji:      '🦘',
        src:        'assets/sprites/duck/duck_jumping.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        10,
        loop:       false,
      },
      {
        id:         'sleepy',
        label:      'Sleepy',
        emoji:      '😴',
        src:        'assets/sprites/duck/duck_sleepy.png',
        cols:       5,
        rows:       2,
        frameCount: 10,
        fps:        4,
        loop:       false,
      },
      {
        id:         'playing',
        label:      'Playing',
        emoji:      '🎈',
        src:        'assets/sprites/duck/duck_playing.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
      {
        id:         'walkin',
        label:      'Walk In',
        emoji:      '✨',
        src:        'assets/sprites/duck/duck_walkin.png',
        cols:       4,
        rows:       2,
        frameCount: 8,
        fps:        10,
        loop:       false,
      },
    ],
  },
];

/* Quick lookup by ID */
export const CHARACTER_MAP = Object.fromEntries(CHARACTERS.map(c => [c.id, c]));
